config/routes.rb
Rails.application.routes.draw do
  get 'developers/restful_api'

  root to: 'home#show'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/sso' => 'auth0#sso'
  get '/auth/logout' => 'auth0#logout'
  get '/docs' => "home#docs"

  resources :users, only: [] do
  	collection do
  		get 'super_admin'
  		get 'admin'
  		get 'manager'
  		get 'developer'
      get 'developers/restful_api'
      match 'autocomplete_sidebar_links' => "users#autocomplete_sidebar_links", :as => :autocomplete_sidebar_links ,via: [ :POST ,:get ]
      get 'logout'
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Secured
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  include ApplicationHelper

  def callback
    # OmniAuth places the User Profile information (retrieved by omniauth-auth0) in request.env['omniauth.auth'].
    # In this tutorial, you will store that info in the session, under 'userinfo'.
    # If the id_token is needed, you can get it from session[:userinfo]['credentials']['id_token'].
    # Refer to https://github.com/auth0/omniauth-auth0#auth-hash for complete information on 'omniauth.auth' contents.
    session[:userinfo] = request.env['omniauth.auth']

    if session[:target_url].present? then
      redirect_to session[:target_url]
      session.delete(:target_url)
    else
      redirect_to get_user_target_url_with_relative_url
    end
  end

  def logout
    if session[:userinfo].present? then
      session.delete(:userinfo)
    end
    redirect_to sprintf("https://%s/v2/logout?federated&returnTo=%s",ENV["AUTH0_DOMAIN"],logout_users_url)
  end

  def sso
    if request.params['target_url'].present? then
      # should actually constrain this to make sure it is a local redirect?  Or only expected redirects.
    else
      redirect_to 'auth/failure?message=target_url is required for this endpoint'
      return
    end
    if not request.params['connection'].present? then
      redirect_to 'auth/failure?message=connection is required for this endpoint'
      return
    end

    if session[:userinfo].present? then
      # User is already logged in, just redirect
      redirect_to params['target_url']
    else
      session[:target_url] = request.params['target_url']
      # Redirect to login
      redirect_to getAuthUrl(connection: request.params['connection'])
    end
  end

  # if user authentication fails on the provider side OmniAuth will redirect to /auth/failure,
  # passing the error message in the 'message' request param.
  def failure
    @error_msg = request.params['message']
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern
  include ApplicationHelper

  def logged_in_using_omniauth?
    redirect_to getAuthUrl() unless session[:userinfo].present?
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  layout "developer_layout"
	before_action :logged_in_using_omniauth?
	before_action :check_authentication

  def restful_api
  end

  private
  def check_authentication
  	unless current_user[:role] === "super_admin" || current_user[:role] === "developer"
  		redirect_to :back, notice: "You are not authorized."
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def docs
    doc_url = ENV['REVERSAND_JEKYLL_PATH'] + ENV["REVERSAND_JEKYLL_DOC"] + params[:page]
    @source = open(doc_url){|f|f.read}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # layout :fetch_layout, except: [:logout]
  before_action :logged_in_using_omniauth?, except: [:logout]
  before_action :get_user_links, only: [:autocomplete_sidebar_links]

  def super_admin
    redirect_to root_path, notice: "You are not authorized." unless current_user[:role] === "super_admin"
    @source = open(ENV["REVERSAND_JEKYLL_PATH"]){|f|f.read}
  end

  def admin
    redirect_to root_path, notice: "You are not authorized." unless current_user[:role] === "admin" || current_user[:role] === "super_admin"
    @source = open(ENV["REVERSAND_JEKYLL_PATH"] + "/admin"){|f|f.read}
  end

  def manager
    redirect_to root_path, notice: "You are not authorized." unless current_user[:role] === "manager" || current_user[:role] === "super_admin"
    @source = open(ENV["REVERSAND_JEKYLL_PATH"] + "/manager"){|f|f.read}
  end

  def developer
    redirect_to root_path, notice: "You are not authorized." unless current_user[:role] === "developer" || current_user[:role] === "super_admin"
    @source = open(ENV["REVERSAND_JEKYLL_PATH"] + "/developer"){|f|f.read}
  end

  def autocomplete_sidebar_links
    require 'json'
    @filter_links = @links.select { |data| data['title'].downcase.include? params[:term].downcase || data['tags'].map{|tag| tag.downcase}.grep(/#{params[:term].downcase}/).any? }
    @documentation = @links.map{|t| t['documentation']}.flatten.compact.uniq
    @versions = @links.map{|t| t['versions']}.flatten.compact.uniq
    @topics = @links.map{|t| t['topics']}.flatten.compact.uniq

    if params[:documentation].present? || params[:version].present? || params[:topic].present?
        @filter_links = @filter_links.select { |a|
        (a['documentation'] & params[:documentation].to_a).present? ||  (a['versions'] & params[:version].to_a).present? ||  (a['topics'] & params[:topic].to_a).present? }
    end

    respond_to do |format|
      format.html { @filter_links = Kaminari.paginate_array(@filter_links).page(params[:page]).per(params[:per] || 10)  }
      format.json {
        @filter_links.present? ? @filter_links : @filter_links = [{"title" => "No results found!", "url" => ""}]
      }
      format.js { @filter_links = Kaminari.paginate_array(@filter_links).page(params[:page]).per(params[:per] || 10) }
    end
  end

  def logout
  end

  private

  def fetch_layout
    case action_name
    when "admin", "manager"
      "manager_layout"
    when "developer"
      "developer_layout"
    else
      "application"
    end
  end

  def get_user_links
    case current_user[:role]
    when "super_admin"
      @links = JSON.parse(File.read("super_admin_links.json")) + JSON.parse(File.read("admin_links.json")) + JSON.parse(File.read("manager_links.json")) + JSON.parse(File.read("developer_links.json"))
    when "admin"
      @links = JSON.parse(File.read("admin_links.json"))
    when "manager"
      @links = JSON.parse(File.read("manager_links.json"))
    when "developer"
      @links = JSON.parse(File.read("developer_links.json"))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def getAuthUrl(connection: 'Username-Password-Authentication')
    return sprintf("#{ENV['RELATIVE_URL']}/auth/auth0?connection=%s",connection)
  end

  def current_user
  	user_data = JSON.parse(session[:userinfo].to_json)["extra"]["raw_info"]
  	return {
  		email: user_data["email"],
  		full_name: user_data["user_metadata"]["full_name"],
  		role: user_data["user_metadata"]["Role"]
  	}
  end

  def is_logged_in?
  	if session[:userinfo].present?
  		true
  	else
  		false
  	end
  end

  def get_user_target_url
    if current_user[:role] == 'super_admin'
      return '/users/super_admin'
    elsif current_user[:role] == 'admin'
      return '/users/admin'
    elsif current_user[:role] == 'manager'
      return '/users/manager'
    elsif current_user[:role] == 'developer'
      return '/users/developer'
    end
  end

  def get_user_target_url_with_relative_url
    return ENV['RELATIVE_URL'] + get_user_target_url
  end
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auth0/failure.html.erb
<div class="panel panel-danger">
  <h2>Error <%= @error_msg %></h2>
  <p><%= @omniauth_error %></p>
</div>

app/views/developers/restful_api.html.erb
<div class="container ">
	<div class="row justify-content-md-end">
		<div class="col-xs-12 col-sm-12 col-md-12 make-small make-same">
			<div class="left-side">
				<div class="color-left-scroller">
					<h4>All Docs</h4>
					<div class="side-nav">
						<ul class="cd-accordion-menu animated">
							<li class="has-children">
								<input type="checkbox" name ="group-1" id="group-1" checked>
								<label for="group-1">Authentication Services</label>
								<ul>
									<li><a class="active">Before you Begin</a></li>
									<li><a>Understanding the Request Headers</a></li>
									<li><a>Generating Authentication Token</a></li>
									<li><a>Sending an API Request</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-2" id="group-2">
								<label for="group-2">Entity Services</label>
								<ul>
									<li><a href="#0">demo link</a></li>
									<li><a href="#0">demo link</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-3" id="group-3">
								<label for="group-3">Entity Model Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-4" id="group-4">
								<label for="group-4">Entity Govern Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-5" id="group-5">
								<label for="group-5">Entity Import Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-6" id="group-6">
								<label for="group-6">Entity Export Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-7" id="group-7">
								<label for="group-7">Configuration Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-8" id="group-8">
								<label for="group-8">Match Search Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-9" id="group-9">
								<label for="group-9">Request Tracking Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-10" id="group-10">
								<label for="group-10">Binary Object Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-11" id="group-11">
								<label for="group-11">Event Services</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-12" id="group-12">
								<label for="group-12">Binary Stream Object Service</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
							<li class="has-children">
								<input type="checkbox" name ="group-13" id="group-13">
								<label for="group-13">Entity Graph Service</label>
								<ul>
									<li><a href="#0">Image</a></li>
									<li><a href="#0">Image</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="right-side">
				<div class="breadcrumb">
					<ul>
						<li><%= link_to "Home", get_user_target_url_with_relative_url %></li>
						<li><%= link_to "Developer", developer_users_path %></li>
						<li>
							<a>Doc <i class="fa fa-caret-down" aria-hidden="true"></i></a>
							<div class="arrow_box">
								<ul>
									<li><a>Developer</a></li>
									<li><a>Developer</a></li>
								</ul>
							</div>
						</li>
					</ul>
					<div class="other-options">
						<div class="next-prev"><a class="prev-next" title="Previous Page"><%= image_tag "prev-icon.png" %></a><a class="prev-next" title="Next Page"><%= image_tag "next-icon.png" %></a></div>
						<div class="print-option"><a title="Print" class="print-bt"><%= image_tag "print-icon.png" %></a></div>
						<div class="pdf-option"><a title="PDF" class="pdf-bt"><%= image_tag "pdf-icon.png" %></a></div>
					</div>
				</div>
				<div class="full-box">
					<div class="loop-box">
						<h2><strong>Get Started</strong></h2>
						<p>
							The primary objective of RDP is to facilitate relevant, trust, and insights on your data through a Data Continuum solution in <strong>Master Data Management (MDM 2.0)</strong>. Data flows in various forms in exploding volume and velocity from various sources and often is heterogeneous in nature. It can be structured data such as customer data or an unstructured data such as a binary files or stream data. See <a>Data Classification</a>, for more information on how data is classified in RDP. Hence, the objective is to achieve maximum benefits of the volume, velocity, and variety of data to enhance the productivity and efficiency. <strong>Riversand Data Framework</strong> provides the building blocks to handle Data in RDP.
						</p>
					</div>
					<div class="loop-box">
						<h2>What constitutes RDF?</h2>
						<p>
							It includes a set of services in the SDK that interact with each other to provide the required business functionality. Exposed services such as Data Services are RESTful in nature and you can leverage these services along with the Riversand User Interface Framework to build Custom Apps based on your business requirements. See Data Framework Architecture, to learn more about the architecture of RDF.
						</p>
					</div>
					<div class="loop-box">
						<h2>Who can use RDF and How to use RDF?</h2>
						<p>
							Based on your requirement, RDF can be used by App Developers and System Integrators.
						</p>
						<ul class="blue-txt">
							<li>RDF for App Developers: As an App developer, using RDF, you can leverage the RESTful services along with UI Element Catalog from the Riversand User Interface Framework to build Custom Apps based on your business requirements. See RDP for Developers, for more information on step-by-step instruction on how as a developer you can use RDP to create custom Apps.</li>
							<li>RDF for System Integrators: As a System Integrator, using RDF, you can leverage the RESTful services to integrate with the external systems to send data to RDP and export the data from RDP. See RDP for System Integrators</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/docs.html.erb
<%= @source.html_safe %>

app/views/layouts/_footer.html.erb
<div class="footer-sp site-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-md-3">
        <h2>Solutions</h2>
        <div class="menu-footer">
          <ul>
            <li><a href="javascript:;">Multi-Domain Master Data Management</a></li>
            <li><a href="javascript:;">Product Information Management (PIM)</a></li>
            <li><a href="javascript:;">Digital Asset Management</a></li>
            <li><a href="javascript:;">Spare Parts Management</a></li>
            <li><a href="javascript:;">Print Solution</a></li>
            <li><a href="javascript:;">Data Integration and Syndication</a></li>
            <li><a href="javascript:;">Customer Information Management</a></li>
            <li><a href="javascript:;">Material Master Management</a></li>
            <li><a href="javascript:;">Data Onboarding</a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-2 col-md-2">
        <h2>Industries</h2>
        <div class="menu-footer">
          <ul>
            <li><a href="javascript:;">Retail</a></li>
            <li><a href="javascript:;">Manufacturing</a></li>
            <li><a href="javascript:;">Distribution</a></li>
            <li><a href="javascript:;">Energy</a></li>
            <li><a href="javascript:;">Healthcare</a></li>
            <li><a href="javascript:;">Food Services</a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-2 col-md-2">
        <h2>Company</h2>
        <div class="menu-footer">
          <ul>
            <li><a href="javascript:;">History</a></li>
            <li><a href="javascript:;">Leadership Team</a></li>
            <li><a href="javascript:;">Clients</a></li>
            <li><a href="javascript:;">Partners</a></li>
            <li><a href="javascript:;">Riversand Colors</a></li>
            <li><a href="javascript:;">News &amp; Events</a></li>
            <li><a href="javascript:;">Webinars</a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-2 col-md-2">
        <h2>Support</h2>
        <div class="menu-footer">
          <ul>
            <li><a href="javascript:;">Careers</a></li>
            <li><a href="javascript:;">Contact Us</a></li>
            <li><a href="javascript:;">Sitemap</a></li>
            <li><a href="javascript:;">Privacy Policy</a></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3">
        <div class="footer-widgets">
          <div class="row logo"><a href="javascript:;" class="logo-footer"></a></div>
          <div class="row">
            <p class="email"><a href="javascript:;">sales@riversand.com</a></p>
          </div>
          <div class="row">
            <p class="phone"><a href="tel:17139348899">+1 713.934.8899</a></p>
          </div>
          <div class="row social">
            <a href="https://www.facebook.com/RiversandTechnologies/" target="_blank" rel="noopener noreferrer">
            <%= image_tag 'icon-facebook-light.svg',height: "30", width: "30" %></a>
            <a href="https://plus.google.com/+Riversandmdm" target="_blank" rel="noopener noreferrer">
            <%= image_tag 'icon-googleplus-light.svg',height: "30", width: "30" %></a>
            <a href="https://twitter.com/riversandmdm" target="_blank" rel="noopener noreferrer">
            <%= image_tag 'icon-twitter-light.svg',height: "30", width: "30" %></a>
            <a href="https://www.youtube.com/user/riversandpim" target="_blank" rel="noopener noreferrer">
            <%= image_tag 'icon-youtube-light.svg',height: "30", width: "30" %></a>
            <a href="https://www.linkedin.com/company/riversand-technologies" target="_blank" rel="noopener noreferrer">
            <%= image_tag 'icon-linkedin-light.svg',height: "30", width: "30" %></a>
          </div>
          <div class="row">
            <p class="copyright">&copy; 2017 Riversand All Rights Reserved.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-2 col-md-2">
        <div class="hamburger">
          <a href="javascript:;" id="c-button--push-left"><img src="assets/hamburger.svg" width="32" height="32"></a>
        </div>
        <div class="logo-holder">
          <!-- <a href="javascript:;"><img src="assets/logo.png" width="166" height="40"></a> -->
          <%= link_to "#{is_logged_in? ? get_user_target_url_with_relative_url : 'javascript:;'}" do %>
            <img src="assets/logo.png" width="166" height="40">
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="search-holder">
        <%= form_tag autocomplete_sidebar_links_users_path, method: :get do %>
          <%= text_field_tag "term", nil, id: "available-link-search-txt", autofocus: true %>
          <div class="results" id="available-link-search-results"></div>
          <button type="submit">search</button>
        <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="others-holders">
          <% if is_logged_in? %>
          <div class="after-login-holder">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
              <div class="pp"><img src="assets/pic.png" width="32" height="32"></div>
              <div class="pro-info"><%= current_user[:full_name] %><br><span><%= current_user[:role] %></span></div>
            </a>
            <div class="dropdown-menu" role="menu">
              <div class="content">
                <ul>
                  <li><h2>My Profile </h2><span><%= current_user[:email] %></span><a href="javascript:;" class="my-setting"></a></li>
                  <li><%= link_to "Logout", auth_logout_path %></li>
                </ul>
              </div>
            </div>
          </div>
          <% end %>
          <div class="contact-holder">
            <a href="mailto:idg@riversand.com">Feedback</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<script>
  new jekyllApp.Links;
</script>

app/views/layouts/_sidebar.html.erb
<nav id="c-menu--push-left" class="c-menu c-menu--push-left">
  <button class="c-menu__close">&larr; Close Menu</button>
  <div class="right-panel">
    <div class="link-block">
      <div class="link-loop">
        <h2>App Docs</h2>
        <ul>
          <li><a href="javascript:;">Overview</a></li>
          <li><a href="javascript:;">Entity Manage</a></li>
          <li><a href="javascript:;">Dashboard</a></li>
          <li><a href="javascript:;">Entitv Search</a></li>
          <li><a href="javascript:;">Ref Data Management</a></li>
        </ul>
      </div>

      <div class="link-loop">
        <h2>SDKS</h2>
        <ul>
          <li><a href="javascript:;">Overview</a></li>
          <li><a href="rdf-sdk.html">RDF-SDK</a></li>
          <li><a href="javascript:;">RUF-SDK</a></li>
          <li><a href="javascript:;">APIS</a></li>
        </ul>
      </div>

      <div class="link-loop">
        <h2>Guides</h2>
        <ul>
          <li><a href="javascript:;">App Development</a></li>
          <li><a href="javascript:;">App Review</a></li>
          <li><a href="javascript:;">Platform Poﬁcies</a></li>
          <li><a href="javascript:;">Privacy & Consent</a></li>
        </ul>
      </div>
    </div>
    <div class="links-massage">
      <a href=""><img src="assets/left-massage-icon.jpg" width="47" height="47"></a>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jekyll Integration app</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if Rails.env.production? %>
    <base href="/ror/sso_client/" />
  <% else %>
    <base href="/" />
  <% end %>
  <%= yield :cdn_code %>
  <%= javascript_include_tag '//cdn.auth0.com/js/lock/10.0.0/lock.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="hand-over"></div>
  <%= render  'layouts/header' %>
  <%#= render 'layouts/sidebar' %>
  <!-- <div class="page-wapper o-wrapper" id="o-wrapper">
    <div class="container"> -->
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <!-- </div>
  </div>
  <div id="c-mask" class="c-mask"></div> -->
  <%#= render 'layouts/footer' %>
</body>
</html>

app/views/users/_entries.html.erb
 <% if @filter_links.count > 0 %>
 	<div class="search-box"><%= page_entries_info filter_links , entry_name: 'Results' %> found for Create app design </div>
 <% end %>
<div class="row justify-content-md-end">
	<div class="col-xs-12 col-sm-12 col-md-12 search-result">
		<% if @filter_links.count > 0 %>
			<% filter_links.each do |filter_link| %>
				<div class="loop-box">
					<h4><%= filter_link['title'] %> | 
					<%= link_to filter_link['url'], filter_link['url'] %></h4>
					<h5>Product PIM | Versions <%= filter_link['versions']&.join(', ') %></h5>
		   			<p>Aug 8, 2016 - You know, apart from the most obvious search engine. And possibly the second most obvious one too.
		    		In fact I'll start again, what are the eight. Create App Design, apart from the most obvious search engine. </p>
				</div>
			<% end %>
		    <%= paginate filter_links, remote: true %>
		<% else %>
			<div class="loop-box">
				<h4 class="align-center">No Result found</h4>
			</div>
		<% end %>
	</div>
</div>               

app/views/users/admin.html.erb
<%= @source.html_safe %>

app/views/users/autocomplete_sidebar_links.html.erb
<div class="search-breadcrump">
	<div class="container ">
        <div class="row justify-content-md-end">
        	<div class="col-xs-12 col-sm-12 col-md-12 make-small">
            	<div class="row make-same">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                    <h2>Search</h2>
                    <%= link_to   "Back To Home",get_user_target_url_with_relative_url %>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="search-field"><input name="" type="text" placeholder="Create App Design"><button type="submit"><img src="/assets/search-icon.jpg"></button></div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
	<div class="container">
	    <div class="row justify-content-md-end">
	        <div class="col-xs-12 col-sm-12 col-md-12 make-small">
				<%= form_tag autocomplete_sidebar_links_users_path, method: :post , remote: true, id: 'search' do %>
	        	
		            <div class="left-search">
		                <div class="refine-search">Refine Search</div>
		                <div class="loop-search">
		                	<h2>Documentation</h2>
		                	<% @documentation.each do |doc| %>
		                		<%= check_box_tag 'documentation[]',doc , false, class: 'test'  %>
		                        <%= doc %><br>
		                	<% end %>
		                </div>
		                
		                <div class="loop-search">
		                	<h2>Versions</h2>
		                	<% @versions.each do |version| %>
		                		<%= check_box_tag 'version[]',version , false, class: 'test'  %>
		                		<%= version %><br>
			                <% end %>
		                </div>
		                
		                <div class="loop-search">
		                	<h2>Topics</h2>
		                	<% @topics.each do |topic| %>
			                	<%= check_box_tag 'topic[]',topic , false, class: 'test'  %>
			                	<%= topic %><br>
			                <% end %>
		                </div>
		                <div>
		                	<%= hidden_field_tag 'term',params[:term] %>
		                </div>
		            </div>
				<% end %>
	            <div class="right-side">
	                <div class="full-box">
	                	<%= render partial: "entries",:locals => {:filter_links =>  @filter_links } %>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
<script type="text/javascript">
	$('.test').click(function(){
		$('#search').submit();
	})
</script>

app/views/users/autocomplete_sidebar_links.js.erb
$('.full-box').html('<%= escape_javascript(render "entries",  :filter_links =>  @filter_links )%>');

app/views/users/developer.html.erb
<%= @source.html_safe %>

app/views/users/logout.html.erb
<div class="page-wapper o-wrapper" id="o-wrapper">
  <div class="container">
    <div class="row justify-content-md-end">
      <div class="col-xs-12 col-sm-12 col-md-12 make-small">
        <div class="logout-panel">
          <div class="logout-icon"><%= image_tag "loguot-icon.png" %></div>
          <p>
            Thank you for using Riversand Data Platform Help Centre.<br>
            You've successfully logged out from the system.<br>
            Please <%= link_to "click here", ENV.fetch('LOGIN_SITE_URL') + "/client_login" %> to login again<br>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/manager.html.erb
<%= @source.html_safe %>

app/views/users/super_admin.html.erb
<%= @source.html_safe %>